# Generated by Django 4.1.6 on 2023-02-21 21:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_is_verified_emailveryfication"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EmailVeryfication",
            new_name="EmailVerification",
        ),
    ]
