# Generated by Django 4.1.6 on 2023-02-02 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_brand', models.CharField(db_index=True, max_length=100, verbose_name='Категория бренд')),
            ],
            options={
                'verbose_name': 'Категория бренд',
                'verbose_name_plural': 'Категории бренда',
            },
        ),
        migrations.CreateModel(
            name='CategoryColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_color', models.CharField(max_length=50, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Категория цвет',
                'verbose_name_plural': 'Категории цвета',
            },
        ),
        migrations.CreateModel(
            name='CategoryGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_gender', models.CharField(max_length=50, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Категория пол',
                'verbose_name_plural': 'Категории пола',
            },
        ),
        migrations.CreateModel(
            name='CategorySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_size', models.CharField(blank=True, max_length=50, verbose_name='Заголовок размеров')),
                ('category_size', models.IntegerField(verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Категория размеров',
                'verbose_name_plural': 'Категории размеров',
            },
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Бренд')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('color', models.CharField(max_length=50, verbose_name='Расцветка')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('realise_date', models.IntegerField(verbose_name='Дата релиза')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото')),
                ('is_special', models.BooleanField(default=False, verbose_name='Эксклюзивность')),
                ('category_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shoes.categorybrand', verbose_name='Категория бренд')),
                ('category_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shoes.categorycolor', verbose_name='Категория цвет')),
                ('category_gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shoes.categorygender', verbose_name='Категория пол')),
                ('category_size', models.ManyToManyField(blank=True, to='shoes.categorysize', verbose_name='Категория размеров')),
            ],
            options={
                'verbose_name': 'Пары',
                'verbose_name_plural': 'Пары',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shoes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shoes.shoes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
