# Generated by Django 4.1.6 on 2023-03-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoes",
            name="stripe_shoes_price_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
